DIRECTORY:
  data: '../data/test'
  model: "./results/train/timm_tf_efficientnetv2_m_20211006034631" 

MODEL: "timm_tf_efficientnetv2_m"

DATALOADER:
  num_workers:
  shuffle: False
  pin_memory:
  drop_last: False

SEED:
  random_seed: 42

PREDICT:
  train_serial:
  batch_size: 64


